sonar.projectKey=amurlaniakea_memlineage
sonar.organization=amurlaniakea
sonar.projectName=memlineage

sonar.sources=src/memlineage
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=tests/**/*.py,**/__pycache__/**,**/*.pyc
sonar.python.version=3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
