sonar.projectKey=amurlaniakea_memlineage
sonar.organization=amurlaniakea
sonar.projectName=memlineage

sonar.sources=src/memlineage
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11,3.12

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc
